version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2X3xKmt50FPnROL4mlz9nb
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --save 30 1 --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres:
    driver: local
  redis:
    driver: local