name: Deploy Backend

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set appsettings.json
        run: echo $DOTNET_APP_SETTINGS > backend/appsettings.json
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
